version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
    groups:
      all-dependencies:
        patterns:
          - "*"
    assignees:
      - "jluszcz"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
    groups:
      all-actions:
        patterns:
          - "*"
    assignees:
      - "jluszcz"
