repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: detect-aws-credentials
        args:
            - --allow-missing-credentials
    -   id: end-of-file-fixer
    -   id: file-contents-sorter
        files: .gitignore
    -   id: trailing-whitespace
