name: CI

on:
  push:
    branches:
      - main

    paths:
      - '.github/workflows/ci.yml'
      - 'Cargo**'
      - 'src/**/*.rs'

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci:
    uses: jluszcz/github-utils/.github/workflows/rust-ci.yml@v1
    with:
      runs-on: ubuntu-24.04-arm
      target: aarch64-unknown-linux-musl

  package:
    needs: ci
    if: github.event_name == 'push'
    uses: jluszcz/github-utils/.github/workflows/lambda-package.yml@v1
    with:
      project: list-of-lists

  deploy:
    needs: package
    if: github.event_name == 'push'
    permissions:
      id-token: write
      contents: read
    uses: jluszcz/github-utils/.github/workflows/deploy-lambda.yml@v1
    with:
      aws-region: us-east-2
      project: list-of-lists
    secrets:
      aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
