name: Update Index Template

on:
  push:
    branches:
      - main

    paths:
      - '.github/workflows/update-index-template.yml'
      - 'index.template'

jobs:
  update-index:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.2.1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/list-of-lists.github-update
          role-session-name: github-upload
          aws-region: us-east-2

      - name: Upload to S3
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: aws s3 cp index.template "s3://list-of-lists-${AWS_ACCOUNT_ID}-${AWS_REGION}-an/"
