name: Update Index Template

on:
  push:
    branches:
      - main

    paths:
      - '.github/workflows/update-index-template.yml'
      - 'index.template'

jobs:
  update-index:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/list-of-lists.github-update
          role-session-name: github-upload
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Upload to S3
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_BUCKET: list-of-lists-${{ secrets.AWS_ACCOUNT_ID }}-${{ AWS_DEFAULT_REGION }}-an
        run: aws s3 cp index.template s3://${AWS_BUCKET}/
